"""Update FK constraints - category RESTRICT, image SET NULL

Revision ID: a50ba3076107
Revises: db711f4ff4fa
Create Date: 2025-12-09 07:19:28.673678

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a50ba3076107'
down_revision = 'db711f4ff4fa'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('recipez_category', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('recipez_category_category_author_id_fkey'), type_='foreignkey')
        batch_op.create_foreign_key(None, 'recipez_user', ['category_author_id'], ['user_id'], referent_schema='recipez', ondelete='CASCADE')

    with op.batch_alter_table('recipez_image', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('recipez_image_image_author_id_fkey'), type_='foreignkey')
        batch_op.create_foreign_key(None, 'recipez_user', ['image_author_id'], ['user_id'], referent_schema='recipez', ondelete='CASCADE')

    with op.batch_alter_table('recipez_ingredient', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('recipez_ingredient_ingredient_author_id_fkey'), type_='foreignkey')
        batch_op.drop_constraint(batch_op.f('recipez_ingredient_ingredient_recipe_id_fkey'), type_='foreignkey')
        batch_op.create_foreign_key(None, 'recipez_user', ['ingredient_author_id'], ['user_id'], referent_schema='recipez', ondelete='CASCADE')
        batch_op.create_foreign_key(None, 'recipez_recipe', ['ingredient_recipe_id'], ['recipe_id'], referent_schema='recipez', ondelete='CASCADE')

    with op.batch_alter_table('recipez_recipe', schema=None) as batch_op:
        batch_op.alter_column('recipe_image_id',
               existing_type=sa.UUID(),
               nullable=True)
        batch_op.drop_constraint(batch_op.f('recipez_recipe_recipe_image_id_fkey'), type_='foreignkey')
        batch_op.drop_constraint(batch_op.f('recipez_recipe_recipe_author_id_fkey'), type_='foreignkey')
        batch_op.drop_constraint(batch_op.f('recipez_recipe_recipe_category_id_fkey'), type_='foreignkey')
        batch_op.create_foreign_key(None, 'recipez_category', ['recipe_category_id'], ['category_id'], referent_schema='recipez', ondelete='RESTRICT')
        batch_op.create_foreign_key(None, 'recipez_image', ['recipe_image_id'], ['image_id'], referent_schema='recipez', ondelete='SET NULL')
        batch_op.create_foreign_key(None, 'recipez_user', ['recipe_author_id'], ['user_id'], referent_schema='recipez', ondelete='CASCADE')

    with op.batch_alter_table('recipez_step', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('recipez_step_step_author_id_fkey'), type_='foreignkey')
        batch_op.drop_constraint(batch_op.f('recipez_step_step_recipe_id_fkey'), type_='foreignkey')
        batch_op.create_foreign_key(None, 'recipez_user', ['step_author_id'], ['user_id'], referent_schema='recipez', ondelete='CASCADE')
        batch_op.create_foreign_key(None, 'recipez_recipe', ['step_recipe_id'], ['recipe_id'], referent_schema='recipez', ondelete='CASCADE')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('recipez_step', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key(batch_op.f('recipez_step_step_recipe_id_fkey'), 'recipez_recipe', ['step_recipe_id'], ['recipe_id'], ondelete='CASCADE')
        batch_op.create_foreign_key(batch_op.f('recipez_step_step_author_id_fkey'), 'recipez_user', ['step_author_id'], ['user_id'], ondelete='CASCADE')

    with op.batch_alter_table('recipez_recipe', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key(batch_op.f('recipez_recipe_recipe_category_id_fkey'), 'recipez_category', ['recipe_category_id'], ['category_id'], ondelete='CASCADE')
        batch_op.create_foreign_key(batch_op.f('recipez_recipe_recipe_author_id_fkey'), 'recipez_user', ['recipe_author_id'], ['user_id'], ondelete='CASCADE')
        batch_op.create_foreign_key(batch_op.f('recipez_recipe_recipe_image_id_fkey'), 'recipez_image', ['recipe_image_id'], ['image_id'], ondelete='CASCADE')
        batch_op.alter_column('recipe_image_id',
               existing_type=sa.UUID(),
               nullable=False)

    with op.batch_alter_table('recipez_ingredient', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key(batch_op.f('recipez_ingredient_ingredient_recipe_id_fkey'), 'recipez_recipe', ['ingredient_recipe_id'], ['recipe_id'], ondelete='CASCADE')
        batch_op.create_foreign_key(batch_op.f('recipez_ingredient_ingredient_author_id_fkey'), 'recipez_user', ['ingredient_author_id'], ['user_id'], ondelete='CASCADE')

    with op.batch_alter_table('recipez_image', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key(batch_op.f('recipez_image_image_author_id_fkey'), 'recipez_user', ['image_author_id'], ['user_id'], ondelete='CASCADE')

    with op.batch_alter_table('recipez_category', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key(batch_op.f('recipez_category_category_author_id_fkey'), 'recipez_user', ['category_author_id'], ['user_id'], ondelete='CASCADE')

    # ### end Alembic commands ###
