"""Add API key management table

Revision ID: b1c2d3e4f5g6
Revises: a50ba3076107
Create Date: 2025-12-11

"""

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "b1c2d3e4f5g6"
down_revision = "a50ba3076107"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "recipez_api_key",
        sa.Column(
            "api_key_id",
            sa.UUID(),
            server_default=sa.text("gen_random_uuid()"),
            nullable=False,
        ),
        sa.Column("api_key_user_id", sa.UUID(), nullable=False),
        sa.Column("api_key_name", sa.Text(), nullable=False),
        sa.Column("api_key_hash", sa.String(length=128), nullable=False),
        sa.Column("api_key_scopes", sa.JSON(), nullable=False),
        sa.Column("api_key_expires_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column(
            "api_key_created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("api_key_revoked_at", sa.DateTime(timezone=True), nullable=True),
        sa.ForeignKeyConstraint(
            ["api_key_user_id"],
            ["recipez.recipez_user.user_id"],
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("api_key_id"),
        schema="recipez",
    )
    # Index for fast lookup by hash during JWT validation
    with op.batch_alter_table("recipez_api_key", schema="recipez") as batch_op:
        batch_op.create_index(
            batch_op.f("ix_recipez_api_key_hash"),
            ["api_key_hash"],
            unique=True,
        )
        batch_op.create_index(
            batch_op.f("ix_recipez_api_key_user_id"),
            ["api_key_user_id"],
            unique=False,
        )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("recipez_api_key", schema="recipez") as batch_op:
        batch_op.drop_index(batch_op.f("ix_recipez_api_key_user_id"))
        batch_op.drop_index(batch_op.f("ix_recipez_api_key_hash"))

    op.drop_table("recipez_api_key", schema="recipez")
    # ### end Alembic commands ###
