"""Remove ingredient unique constraint to allow duplicate ingredients

This migration removes the unique constraint on (ingredient_name, ingredient_quantity,
ingredient_measurement, ingredient_recipe_id) from the recipez_ingredient table.

The constraint was causing errors when AI-generated recipes contained duplicate ingredients
(e.g., same ingredient used twice in different parts of a recipe). Each ingredient already
has a unique ingredient_id (UUID) which is sufficient for data integrity.

Revision ID: c7d8e9f0a1b2
Revises: b1c2d3e4f5g6
Create Date: 2025-12-14

"""

from alembic import op


# revision identifiers, used by Alembic.
revision = "c7d8e9f0a1b2"
down_revision = "b1c2d3e4f5g6"
branch_labels = None
depends_on = None


def upgrade():
    # Drop the unique constraint on ingredients
    # The constraint was auto-generated by PostgreSQL with a truncated name
    # Format: {table}_{columns...}_key (truncated at 63 chars)
    op.drop_constraint(
        "recipez_ingredient_ingredient_name_ingredient_quantity_ingre_key",
        "recipez_ingredient",
        type_="unique"
    )


def downgrade():
    # Re-add the unique constraint if needed (rollback)
    op.create_unique_constraint(
        "recipez_ingredient_ingredient_name_ingredient_quantity_ingre_key",
        "recipez_ingredient",
        ["ingredient_name", "ingredient_quantity", "ingredient_measurement", "ingredient_recipe_id"]
    )
