"""Change recipe_name from global unique to per-user unique

This migration changes the recipe_name constraint from globally unique to
unique per author. This allows different users to create recipes with the
same name (e.g., multiple users can have their own "Chocolate Cake").

Before: recipe_name must be unique across ALL users
After: recipe_name must be unique only within each user's recipes

Revision ID: d8e9f0a1b2c3
Revises: c7d8e9f0a1b2
Create Date: 2025-12-14

"""

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "d8e9f0a1b2c3"
down_revision = "c7d8e9f0a1b2"
branch_labels = None
depends_on = None


def upgrade():
    # Drop the global unique constraint on recipe_name
    # Table is in 'recipez' schema, constraint was auto-generated by PostgreSQL
    op.drop_constraint(
        "recipez_recipe_recipe_name_key",
        "recipez_recipe",
        type_="unique",
        schema="recipez"
    )

    # Add composite unique constraint (per-user uniqueness)
    # Each user can have their own "Chocolate Cake" but can't duplicate within their recipes
    op.create_unique_constraint(
        "uq_recipe_name_per_author",
        "recipez_recipe",
        ["recipe_name", "recipe_author_id"],
        schema="recipez"
    )


def downgrade():
    # Remove the per-user unique constraint
    op.drop_constraint(
        "uq_recipe_name_per_author",
        "recipez_recipe",
        type_="unique",
        schema="recipez"
    )

    # Restore global unique constraint on recipe_name
    # NOTE: This may fail if duplicate recipe names now exist across users
    op.create_unique_constraint(
        "recipez_recipe_recipe_name_key",
        "recipez_recipe",
        ["recipe_name"],
        schema="recipez"
    )
