"""Remove recipe_description_preview column

Revision ID: db711f4ff4fa
Revises: fbc3b00ffc0a
Create Date: 2025-12-09 07:05:54.374268

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'db711f4ff4fa'
down_revision = 'fbc3b00ffc0a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('recipez_category', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('recipez_category_category_author_id_fkey'), type_='foreignkey')
        batch_op.create_foreign_key(None, 'recipez_user', ['category_author_id'], ['user_id'], referent_schema='recipez', ondelete='CASCADE')

    with op.batch_alter_table('recipez_image', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('recipez_image_image_author_id_fkey'), type_='foreignkey')
        batch_op.create_foreign_key(None, 'recipez_user', ['image_author_id'], ['user_id'], referent_schema='recipez', ondelete='CASCADE')

    with op.batch_alter_table('recipez_ingredient', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('recipez_ingredient_ingredient_author_id_fkey'), type_='foreignkey')
        batch_op.drop_constraint(batch_op.f('recipez_ingredient_ingredient_recipe_id_fkey'), type_='foreignkey')
        batch_op.create_foreign_key(None, 'recipez_recipe', ['ingredient_recipe_id'], ['recipe_id'], referent_schema='recipez', ondelete='CASCADE')
        batch_op.create_foreign_key(None, 'recipez_user', ['ingredient_author_id'], ['user_id'], referent_schema='recipez', ondelete='CASCADE')

    with op.batch_alter_table('recipez_recipe', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('recipez_recipe_recipe_author_id_fkey'), type_='foreignkey')
        batch_op.drop_constraint(batch_op.f('recipez_recipe_recipe_image_id_fkey'), type_='foreignkey')
        batch_op.drop_constraint(batch_op.f('recipez_recipe_recipe_category_id_fkey'), type_='foreignkey')
        batch_op.create_foreign_key(None, 'recipez_image', ['recipe_image_id'], ['image_id'], referent_schema='recipez', ondelete='CASCADE')
        batch_op.create_foreign_key(None, 'recipez_category', ['recipe_category_id'], ['category_id'], referent_schema='recipez', ondelete='CASCADE')
        batch_op.create_foreign_key(None, 'recipez_user', ['recipe_author_id'], ['user_id'], referent_schema='recipez', ondelete='CASCADE')
        batch_op.drop_column('recipe_description_preview')

    with op.batch_alter_table('recipez_step', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('recipez_step_step_recipe_id_fkey'), type_='foreignkey')
        batch_op.drop_constraint(batch_op.f('recipez_step_step_author_id_fkey'), type_='foreignkey')
        batch_op.create_foreign_key(None, 'recipez_recipe', ['step_recipe_id'], ['recipe_id'], referent_schema='recipez', ondelete='CASCADE')
        batch_op.create_foreign_key(None, 'recipez_user', ['step_author_id'], ['user_id'], referent_schema='recipez', ondelete='CASCADE')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('recipez_step', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key(batch_op.f('recipez_step_step_author_id_fkey'), 'recipez_user', ['step_author_id'], ['user_id'], ondelete='CASCADE')
        batch_op.create_foreign_key(batch_op.f('recipez_step_step_recipe_id_fkey'), 'recipez_recipe', ['step_recipe_id'], ['recipe_id'], ondelete='CASCADE')

    with op.batch_alter_table('recipez_recipe', schema=None) as batch_op:
        batch_op.add_column(sa.Column('recipe_description_preview', sa.TEXT(), autoincrement=False, nullable=False))
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key(batch_op.f('recipez_recipe_recipe_category_id_fkey'), 'recipez_category', ['recipe_category_id'], ['category_id'], ondelete='CASCADE')
        batch_op.create_foreign_key(batch_op.f('recipez_recipe_recipe_image_id_fkey'), 'recipez_image', ['recipe_image_id'], ['image_id'], ondelete='CASCADE')
        batch_op.create_foreign_key(batch_op.f('recipez_recipe_recipe_author_id_fkey'), 'recipez_user', ['recipe_author_id'], ['user_id'], ondelete='CASCADE')

    with op.batch_alter_table('recipez_ingredient', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key(batch_op.f('recipez_ingredient_ingredient_recipe_id_fkey'), 'recipez_recipe', ['ingredient_recipe_id'], ['recipe_id'], ondelete='CASCADE')
        batch_op.create_foreign_key(batch_op.f('recipez_ingredient_ingredient_author_id_fkey'), 'recipez_user', ['ingredient_author_id'], ['user_id'], ondelete='CASCADE')

    with op.batch_alter_table('recipez_image', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key(batch_op.f('recipez_image_image_author_id_fkey'), 'recipez_user', ['image_author_id'], ['user_id'], ondelete='CASCADE')

    with op.batch_alter_table('recipez_category', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key(batch_op.f('recipez_category_category_author_id_fkey'), 'recipez_user', ['category_author_id'], ['user_id'], ondelete='CASCADE')

    # ### end Alembic commands ###
