"""Initiall migration

Revision ID: f40725b4d7c5
Revises: 
Create Date: 2025-06-03 06:46:40.658541

"""

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "f40725b4d7c5"
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "recipez_code",
        sa.Column(
            "code_id",
            sa.UUID(),
            server_default=sa.text("gen_random_uuid()"),
            nullable=False,
        ),
        sa.Column("code_count", sa.Integer(), nullable=False),
        sa.Column("code_value", sa.String(), nullable=False),
        sa.Column("code_issued_at", sa.DateTime(), nullable=True),
        sa.Column("code_expires_at", sa.DateTime(), nullable=True),
        sa.Column("code_attempts", sa.Integer(), nullable=False),
        sa.Column("code_cooldown", sa.DateTime(), nullable=True),
        sa.Column("code_email", sa.String(), nullable=False),
        sa.Column("code_session_id", sa.UUID(), nullable=False),
        sa.PrimaryKeyConstraint("code_id"),
        sa.UniqueConstraint("code_value"),
        schema="recipez",
    )
    op.create_table(
        "recipez_session",
        sa.Column(
            "id", sa.UUID(), server_default=sa.text("gen_random_uuid()"), nullable=False
        ),
        sa.Column("session_id", sa.String(length=255), nullable=True),
        sa.Column("data", sa.LargeBinary(), nullable=False),
        sa.Column("expiry", sa.DateTime(timezone=True), nullable=False),
        sa.PrimaryKeyConstraint("id"),
        schema="recipez",
    )
    op.create_table(
        "recipez_user",
        sa.Column(
            "user_id",
            sa.UUID(),
            server_default=sa.text("gen_random_uuid()"),
            nullable=False,
        ),
        sa.Column(
            "user_sub",
            sa.UUID(),
            server_default=sa.text("gen_random_uuid()"),
            nullable=False,
        ),
        sa.Column("user_email", sa.Text(), nullable=False),
        sa.Column("user_email_hmac", sa.String(length=128), nullable=False),
        sa.Column("user_name", sa.Text(), nullable=False),
        sa.Column("user_created_at", sa.DateTime(), nullable=True),
        sa.PrimaryKeyConstraint("user_id"),
        sa.UniqueConstraint("user_email"),
        sa.UniqueConstraint("user_name"),
        schema="recipez",
    )
    with op.batch_alter_table("recipez_user", schema=None) as batch_op:
        batch_op.create_index(
            batch_op.f("ix_recipez_recipez_user_user_email_hmac"),
            ["user_email_hmac"],
            unique=True,
        )

    op.create_table(
        "recipez_category",
        sa.Column(
            "category_id",
            sa.UUID(),
            server_default=sa.text("gen_random_uuid()"),
            nullable=False,
        ),
        sa.Column("category_name", sa.String(), nullable=False),
        sa.Column("category_author_id", sa.UUID(), nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=True),
        sa.ForeignKeyConstraint(
            ["category_author_id"], ["recipez.recipez_user.user_id"], ondelete="CASCADE"
        ),
        sa.PrimaryKeyConstraint("category_id"),
        sa.UniqueConstraint("category_name"),
        schema="recipez",
    )
    op.create_table(
        "recipez_image",
        sa.Column(
            "image_id",
            sa.UUID(),
            server_default=sa.text("gen_random_uuid()"),
            nullable=False,
        ),
        sa.Column("image_url", sa.String(), nullable=False),
        sa.Column("image_author_id", sa.UUID(), nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=True),
        sa.ForeignKeyConstraint(
            ["image_author_id"], ["recipez.recipez_user.user_id"], ondelete="CASCADE"
        ),
        sa.PrimaryKeyConstraint("image_id"),
        schema="recipez",
    )
    op.create_table(
        "recipez_recipe",
        sa.Column(
            "recipe_id",
            sa.UUID(),
            server_default=sa.text("gen_random_uuid()"),
            nullable=False,
        ),
        sa.Column("recipe_name", sa.String(), nullable=False),
        sa.Column("recipe_description", sa.Text(), nullable=False),
        sa.Column("recipe_description_preview", sa.Text(), nullable=False),
        sa.Column("recipe_category_id", sa.UUID(), nullable=False),
        sa.Column("recipe_image_id", sa.UUID(), nullable=False),
        sa.Column("recipe_author_id", sa.UUID(), nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=True),
        sa.ForeignKeyConstraint(
            ["recipe_author_id"], ["recipez.recipez_user.user_id"], ondelete="CASCADE"
        ),
        sa.ForeignKeyConstraint(
            ["recipe_category_id"],
            ["recipez.recipez_category.category_id"],
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["recipe_image_id"], ["recipez.recipez_image.image_id"], ondelete="CASCADE"
        ),
        sa.PrimaryKeyConstraint("recipe_id"),
        sa.UniqueConstraint("recipe_name"),
        schema="recipez",
    )
    op.create_table(
        "recipez_step",
        sa.Column(
            "step_id",
            sa.UUID(),
            server_default=sa.text("gen_random_uuid()"),
            nullable=False,
        ),
        sa.Column("step_text", sa.Text(), nullable=False),
        sa.Column("step_author_id", sa.UUID(), nullable=False),
        sa.Column("step_recipe_id", sa.UUID(), nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=True),
        sa.ForeignKeyConstraint(
            ["step_author_id"], ["recipez.recipez_user.user_id"], ondelete="CASCADE"
        ),
        sa.ForeignKeyConstraint(
            ["step_recipe_id"], ["recipez.recipez_recipe.recipe_id"], ondelete="CASCADE"
        ),
        sa.PrimaryKeyConstraint("step_id"),
        schema="recipez",
    )
    op.create_table(
        "recipez_ingredient",
        sa.Column(
            "ingredient_id",
            sa.UUID(),
            server_default=sa.text("gen_random_uuid()"),
            nullable=False,
        ),
        sa.Column("ingredient_name", sa.String(), nullable=False),
        sa.Column("ingredient_quantity", sa.String(), nullable=False),
        sa.Column("ingredient_measurement", sa.String(), nullable=False),
        sa.Column("ingredient_author_id", sa.UUID(), nullable=False),
        sa.Column("ingredient_recipe_id", sa.UUID(), nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=True),
        sa.ForeignKeyConstraint(
            ["ingredient_author_id"],
            ["recipez.recipez_user.user_id"],
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["ingredient_recipe_id"],
            ["recipez.recipez_recipe.recipe_id"],
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("ingredient_id"),
        sa.UniqueConstraint(
            "ingredient_name",
            "ingredient_quantity",
            "ingredient_measurement",
            "ingredient_recipe_id",
        ),
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("recipez_ingredient")
    op.drop_table("recipez_step", schema="recipez")
    op.drop_table("recipez_recipe", schema="recipez")
    op.drop_table("recipez_image", schema="recipez")
    op.drop_table("recipez_category", schema="recipez")
    with op.batch_alter_table("recipez_user", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_recipez_recipez_user_user_email_hmac"))

    op.drop_table("recipez_user", schema="recipez")
    op.drop_table("recipez_session", schema="recipez")
    op.drop_table("recipez_code", schema="recipez")
    # ### end Alembic commands ###
