"""add user_profile_image_url to recipez_user

Revision ID: fbc3b00ffc0a
Revises: f40725b4d7c5
Create Date: 2025-08-12 16:10:30.474779

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'fbc3b00ffc0a'
down_revision = 'f40725b4d7c5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('recipez_category', schema=None) as batch_op:
        batch_op.drop_constraint('recipez_category_category_author_id_fkey', type_='foreignkey')
        batch_op.create_foreign_key(None, 'recipez_user', ['category_author_id'], ['user_id'], referent_schema='recipez', ondelete='CASCADE')

    with op.batch_alter_table('recipez_image', schema=None) as batch_op:
        batch_op.drop_constraint('recipez_image_image_author_id_fkey', type_='foreignkey')
        batch_op.create_foreign_key(None, 'recipez_user', ['image_author_id'], ['user_id'], referent_schema='recipez', ondelete='CASCADE')

    with op.batch_alter_table('recipez_ingredient', schema=None) as batch_op:
        batch_op.drop_constraint('recipez_ingredient_ingredient_recipe_id_fkey', type_='foreignkey')
        batch_op.drop_constraint('recipez_ingredient_ingredient_author_id_fkey', type_='foreignkey')
        batch_op.create_foreign_key(None, 'recipez_user', ['ingredient_author_id'], ['user_id'], referent_schema='recipez', ondelete='CASCADE')
        batch_op.create_foreign_key(None, 'recipez_recipe', ['ingredient_recipe_id'], ['recipe_id'], referent_schema='recipez', ondelete='CASCADE')

    with op.batch_alter_table('recipez_recipe', schema=None) as batch_op:
        batch_op.drop_constraint('recipez_recipe_recipe_image_id_fkey', type_='foreignkey')
        batch_op.drop_constraint('recipez_recipe_recipe_author_id_fkey', type_='foreignkey')
        batch_op.drop_constraint('recipez_recipe_recipe_category_id_fkey', type_='foreignkey')
        batch_op.create_foreign_key(None, 'recipez_category', ['recipe_category_id'], ['category_id'], referent_schema='recipez', ondelete='CASCADE')
        batch_op.create_foreign_key(None, 'recipez_user', ['recipe_author_id'], ['user_id'], referent_schema='recipez', ondelete='CASCADE')
        batch_op.create_foreign_key(None, 'recipez_image', ['recipe_image_id'], ['image_id'], referent_schema='recipez', ondelete='CASCADE')

    with op.batch_alter_table('recipez_step', schema=None) as batch_op:
        batch_op.drop_constraint('recipez_step_step_author_id_fkey', type_='foreignkey')
        batch_op.drop_constraint('recipez_step_step_recipe_id_fkey', type_='foreignkey')
        batch_op.create_foreign_key(None, 'recipez_user', ['step_author_id'], ['user_id'], referent_schema='recipez', ondelete='CASCADE')
        batch_op.create_foreign_key(None, 'recipez_recipe', ['step_recipe_id'], ['recipe_id'], referent_schema='recipez', ondelete='CASCADE')

    with op.batch_alter_table('recipez_user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('user_profile_image_url', sa.Text(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('recipez_user', schema=None) as batch_op:
        batch_op.drop_column('user_profile_image_url')

    with op.batch_alter_table('recipez_step', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key('recipez_step_step_recipe_id_fkey', 'recipez_recipe', ['step_recipe_id'], ['recipe_id'], ondelete='CASCADE')
        batch_op.create_foreign_key('recipez_step_step_author_id_fkey', 'recipez_user', ['step_author_id'], ['user_id'], ondelete='CASCADE')

    with op.batch_alter_table('recipez_recipe', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key('recipez_recipe_recipe_category_id_fkey', 'recipez_category', ['recipe_category_id'], ['category_id'], ondelete='CASCADE')
        batch_op.create_foreign_key('recipez_recipe_recipe_author_id_fkey', 'recipez_user', ['recipe_author_id'], ['user_id'], ondelete='CASCADE')
        batch_op.create_foreign_key('recipez_recipe_recipe_image_id_fkey', 'recipez_image', ['recipe_image_id'], ['image_id'], ondelete='CASCADE')

    with op.batch_alter_table('recipez_ingredient', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key('recipez_ingredient_ingredient_author_id_fkey', 'recipez_user', ['ingredient_author_id'], ['user_id'], ondelete='CASCADE')
        batch_op.create_foreign_key('recipez_ingredient_ingredient_recipe_id_fkey', 'recipez_recipe', ['ingredient_recipe_id'], ['recipe_id'], ondelete='CASCADE')

    with op.batch_alter_table('recipez_image', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key('recipez_image_image_author_id_fkey', 'recipez_user', ['image_author_id'], ['user_id'], ondelete='CASCADE')

    with op.batch_alter_table('recipez_category', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key('recipez_category_category_author_id_fkey', 'recipez_user', ['category_author_id'], ['user_id'], ondelete='CASCADE')

    # ### end Alembic commands ###
